### ISSUE TITLE
Max size of probes

### ISSUE THREAD

**Issue by studywolf** [ctn-archive/nengo_theano#12]
There is a limit of 1000 timesteps for the probes at the minute, this should be dynamic. Maybe doubling the buffer size whenever the limit is hit.

**Comment by hunse** [comment]
Look again. The size starts at 1000, but increases by 1000 when necessary. I also thought about doubling, but I thought that could occasionally end up with a huge buffer. Admittedly, I haven't tested the dynamic resizing part of the code yet, so it might not work as advertised.

**Comment by studywolf** [comment]
Look again again! It doesn't work :S When I change the time on the enc_test to something large the probe breaks
