### ISSUE TITLE
unoptimized dot in test_runtime.py

### ISSUE THREAD

**Issue by jaberg** [ctn-archive/nengo_theano#17]
Maybe a dtype mismatch or something?

**Comment by studywolf** [comment]
that's probably 
https://github.com/ctn-waterloo/nef-py/blob/master/nef/nef_theano/ensemble.py#L411
or 
https://github.com/ctn-waterloo/nef-py/blob/master/nef/nef_theano/ensemble_origin.py#L179

i just hacked these together to get it to work, but I think TT.batched_dot could be used here instead, I meant to flag it and pass it along to you to see if you had thoughts on a better implementation @jaberg !

**Comment by studywolf** [comment]
indeed it was a dtype mismatch! on the transform, casted to float32 and we're golden
