### ISSUE TITLE
encoders / decoders as shared variables

### ISSUE THREAD

**Issue by studywolf** [ctn-archive/nengo_theano#19]
Related to James' update, is there any reason for encoders and decoders to not be shared variables? And if they should be, let's go ahead and implement them as shared the whole way through instead of just in the update function, to try to keep things clean and consistent.

**Comment by tcstewar** [comment]
No particular reason, other than I was noticing that I didn't actually need to keep a copy of them around anywhere when I implemented it, so I didn't bother.
