### ISSUE TITLE
rename python import directory

### ISSUE THREAD

**Issue by jaberg** [ctn-archive/nengo_theano#33]
Currently nengo_theano has two python dirs called "nengo" and "nef" which will either be non-standard (nef) or clash with the ref-impl (nengo). So maybe the import directory name should be... nengo_theano?

**Comment by jaberg** [comment]
Update: apparently the nef folder was empty except for one test. I moved the test into the nengo/test directory. So now the question is just what to do with the "nengo" import dir, which clashes with the ref impl.

**Comment by tbekolay** [comment]
I though the idea was that each backend would just add to the nengo namespace?

**Comment by jaberg** [comment]
Isn't that what the scikits tried to do, and it turned out to be so hard
that they abandoned it?

**Comment by jaberg** [comment]
It's just not an pattern that the setuptools etc. facilitate.

**Comment by tbekolay** [comment]
Okay. I thought the idea was to have something like

``` python
import nengo
model = nengo.model('My Model', backend='theano')
```

rather than

``` python
import nengo_theano as nengo
model = nengo.model('My Model')
```

Has that changed?

**Comment by jaberg** [comment]
Right, that should still work. I was talking about the fact that you can't
have ref-impl and nengo_theano both installing the "nengo" root folder in
the Python path.

**Comment by jaberg** [comment]
In other words, nengo.model('My Model', backend='theano') might need to
import something. So (a) it needs to know what to import, and (b) the thing
it imports has to be called something other than "nengo"

**Comment by tbekolay** [comment]
Ah, okay. So it would be in the nengo_theano namespace, but the reference implementation (which everyone has to install regardless?) would try to import that to populate the backends list?

**Comment by jaberg** [comment]
Right, that's what I had in mind.

**Comment by jaberg** [comment]
The common pattern is that nengo ref-impl is hard-coded with a list of
known backend repos that it would try to import, or there is a config file
somewhere that identifies backends, and the ref-impl uses that file to
interpret backend names.  I'm thinking of it like a plugin architecture.

**Comment by tbekolay** [comment]
Cool, sounds good.

**Comment by studywolf** [comment]
Is this closeable?

**Comment by tbekolay** [comment]
No, the nengo folder at the root should be renamed to `nengo_theano` and the `setup.py` changed so that this repository installs to the `nengo_theano`, so that `nengo` and `nengo_theano` can coexist in site-packages.
