### ISSUE TITLE
why are neurons in a subdir?

### ISSUE THREAD

**Issue by jaberg** [ctn-archive/nengo_theano#34]
Could we just move neurons to the main code dir like everything else?

**Comment by studywolf** [comment]
just a holdover from the first implementation, I think this was an optimistic idea where there would be a bunch of different neuron models and this is where they would be stored.

**Comment by jaberg** [comment]
I suggest flattening the file structure for ease of editing.

**Comment by studywolf** [comment]
sounds good to me!
