### ISSUE TITLE
Noise

### ISSUE THREAD

**Issue by studywolf** [ctn-archive/nengo_theano#6]
Being able to add noise to ensembles, as in Nengo, where you can specify the noise value range for drawing from the uniform distribution over (-noise, noise) and the frequency at which the noise updates.

**Comment by studywolf** [comment]
Noise has been added, but there are a couple of notes: 

First, noise_freq is going to be a pain to implement, because ensembles don't keep track of the current time. Currently instead the noise is resampled every timestep. This works fine, don't know if it's worth the trouble to implement noise_freq.

Second thing is that I added a noise_type parameter, because Nengo was adding noise from a uniform distribution. This is the default type of noise added to the input current but it's also possible now to specify the noise to be Gaussian, in case you want Gaussian white noise.

**Comment by hunse** [comment]
I added the proper scaling to the noise processes. When simulating a white noise process (i.e., no maximum frequency), the process has to be multiplied by sqrt(dt) instead of dt during numerical integration, so I changed the code accordingly.
